"""auto anomalies

Revision ID: 4037881c40ac
Revises: dc7e241110cc
Create Date: 2026-08-04 09:25:06.645305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4037881c40ac'
down_revision: Union[str, Sequence[str], None] = 'dc7e241110cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=True),
    sa.Column('source_ip', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalies_id'), 'anomalies', ['id'], unique=False)
    op.create_index(op.f('ix_anomalies_log_id'), 'anomalies', ['log_id'], unique=False)
    op.create_index(op.f('ix_anomalies_source_ip'), 'anomalies', ['source_ip'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anomalies_source_ip'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_log_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_id'), table_name='anomalies')
    op.drop_table('anomalies')
    # ### end Alembic commands ###
